"""empty message

Revision ID: b1fae0fc4
Revises: 4a7d339832
Create Date: 2015-10-14 18:29:02.474598

"""

# revision identifiers, used by Alembic.
revision = 'b1fae0fc4'
down_revision = '4a7d339832'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
